name: Auto Release ZIP

on:
  push:
    branches:
      - PublishHttps
      - PublishHttp
      - PublishAll

jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip EXE
        run: |
        
    $src = Join-Path $PWD 'HiloPlugin.exe'
    $dst = Join-Path $PWD "HiloPlugin.zip"

    if (Test-Path $dst) { Remove-Item $dst -Force }

    # chỉ nén đúng 1 file
    Compress-Archive -Path $src -DestinationPath $dst -Force
        # Giả sử HiloPlugin.exe đã được push lên repo trong nhánh

      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name == 'PublishHttps' && 'https-latest' || github.ref_name == 'PublishHttp' && 'http-latest' || 'all-latest' }}
          files: HiloSignature-${{ github.ref_name }}.zip
          name: Latest ${{ github.ref_name }} Build
          body: Auto-updated release for ${{ github.ref_name }}
          target_commitish: ${{ github.sha }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}