name: Auto Release EXE

on:
  push:
    branches:
      - PublishHttps
      - PublishHttp
      - PublishAll

jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ClamAV
        run: |
          choco install clamav --force
          freshclam
        shell: powershell

      - name: Scan ZIP and EXE for viruses
        run: |
          clamscan --infected --recursive --no-summary ./HiloPlugin.zip ./HiloPlugin.exe
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Virus detected! Aborting release."
            exit 1
          }
        shell: powershell

      - name: Update Release
        uses: softprops/action-gh-release@v2
        if: success() # Chỉ chạy nếu scan pass
        with:
          tag_name: ${{ github.ref_name == 'PublishHttps' && 'https-latest' || github.ref_name == 'PublishHttp' && 'http-latest' || 'all-latest' }}
          files: |
            ./HiloPlugin.zip
            ./HiloPlugin.exe
          name: Latest Build ${{ github.ref_name }}
          body: Auto-updated release for ${{ github.ref_name }}
          target_commitish: ${{ github.sha }}
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}