name: Auto Release ZIP

on:
  push:
    branches:
      - PublishHttps
      - PublishHttp
      - PublishAll

jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip EXE
        run: |
          if (Test-Path ./HiloPlugin.exe) {
            Compress-Archive -Path ./HiloPlugin.exe -DestinationPath ./HiloPlugin.zip
          } else {
            echo "HiloPlugin.exe not found!"
            exit 1
          }

      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name == 'PublishHttps' && 'https-latest' || github.ref_name == 'PublishHttp' && 'http-latest' || 'all-latest' }}
          files: ./HiloPlugin.zip  # Sửa lại tên file zip cho khớp
          name: Latest Build ${{ github.ref_name }}
          body: Auto-updated release for ${{ github.ref_name }}
          target_commitish: ${{ github.sha }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}